<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jamon</string>
	</array>
	<key>name</key>
	<string>Jamon</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;%)([a-zA-Z0-9:]++)(?=[^&gt;]*&gt;&lt;/\2&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.jamon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.jamon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)(&lt;)(/%)(\2)(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.jamon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.jamon meta.scope.between-tag-pair.jamon</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.jamon</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.jamon</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.jamon</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.any.jamon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%doc&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.jamon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/%doc&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.jamon</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.jamon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^(&lt;/%)</string>
					<key>name</key>
					<string>comment.block.jamon</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%import&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.import.jamon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/%import&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.import.jamon</string>
				</dict>
			</dict>
			<key>name</key>
			<string>storage.modifier.import.jamon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%args&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.args.jamon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/%args&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.args.jamon</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.parameter.jamon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%xargs&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.xargs.jamon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/%xargs&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.xargs.jamon</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.parameter.jamon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%extends</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.extends.jamon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.extends.jamon</string>
				</dict>
			</dict>
			<key>name</key>
			<string>storage.modifier.extends.jamon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%def ([a-zA-Z0-9]+)&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.def.jamon</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.jamon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/%def&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.def.jamon</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.method.jamon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%if(.+)%&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.if.jamon</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.jamon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/%if&gt;)|(&lt;%else&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.if.jamon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.else.jamon</string>
				</dict>
			</dict>
			<key>name</key>
			<string>keyword.control.jamon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%else&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.else.jamon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/%if&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.if.jamon</string>
				</dict>
			</dict>
			<key>name</key>
			<string>keyword.control.else.jamon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%for (.+)%&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.for.jamon</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.jamon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/%for&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.for.jamon</string>
				</dict>
			</dict>
			<key>name</key>
			<string>keyword.control.jamon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;%abstract&gt;</string>
			<key>name</key>
			<string>punctuation.definition.abstract.jamon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%java&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.java.jamon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/%java&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.java.jamon</string>
				</dict>
			</dict>
			<key>name</key>
			<string>punctuation.definition.java.jamon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;% ^(%&gt;)+</string>
			<key>end</key>
			<string>%&gt;</string>
			<key>name</key>
			<string>meta.method.jamon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;&amp; ^(&amp;&gt;)+</string>
			<key>end</key>
			<string>&amp;&gt;</string>
			<key>name</key>
			<string>meta.template.jamon</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.jamon</string>
	<key>uuid</key>
	<string>fadaa18d-154c-45fb-98e3-64c3f4e4cbeb</string>
</dict>
</plist>
